import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import TrpcProvider from "@/components/providers/trpc-providers";

import { cn } from "@/lib/utils";
import "@/style/globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <TrpcProvider>
        <body
          className={cn(
            "grainy min-h-screen bg-background font-sans antialiased ",
            fontSans.variable,
          )}
        >
          {children}
          <Toaster />
        </body>
      </TrpcProvider>
    </html>
  );
}
